### ISSUE TITLE
Do you know any algorithm in Julia Programming Language?

### ISSUE THREAD

**Issue by abrahamcalf** [AllAlgorithms/julia#1]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Julia](https://github.com/AllAlgorithms/julia) this case

**Comment by munozariasjm** [comment]
It would be nice to add a Radial Basis Function's interpolation.
